version: "3.9"

services:

  postgres:
    container_name: postgres_netsepio
    image: postgres:15
    mem_limit: 1536MB
    mem_reservation: 1G
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - netsepio
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_netsepio
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - netsepio
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:

networks:
  netsepio:
    driver: bridge