name: "Build and Push to GHCR"

on:
  push:
    branches: 
      - main
      - prod
      - thisisommore/automated-deployment-82

jobs:

  Deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Build and Push Docker Image
      run: |
        export CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
        export TAG=$([[ $CURRENT_BRANCH == $(basename ${{ github.ref }}) ]] && echo $CURRENT_BRANCH || echo "latest")
        export GITHUB_REF_IMAGE=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
        export GITHUB_BRANCH_IMAGE=ghcr.io/$GITHUB_REPOSITORY:$TAG
        export GITHUB_REF_IMAGE=$(echo $GITHUB_REF_IMAGE | tr '[:upper:]' '[:lower:]')
        export GITHUB_BRANCH_IMAGE=$(echo $GITHUB_BRANCH_IMAGE | tr '[:upper:]' '[:lower:]')
        docker build -t $GITHUB_REF_IMAGE -t $GITHUB_BRANCH_IMAGE .
        echo "Pushing Image to GitHub Container Registry"
        docker push $GITHUB_REF_IMAGE
        docker push $GITHUB_BRANCH_IMAGE
    - name: Deploy on DEV server 
      if: github.ref == 'refs/heads/thisisommore/automated-deployment-82' 
      uses: appleboy/ssh-action@v0.1.7
      with:         
        host: ${{ secrets.DEV_REMOTE_SERVER_ADDRESS }}
        username: ${{ secrets.DEV_SERVER_USERNAME }}
        key:  ${{ secrets.DEV_REMOTE_SERVER_KEY }}
        port: ${{ secrets.DEV_SSH_PORT }} 
        script: |
          pwd
          cd gateway
          docker stop gateway && docker rm gateway && docker image rm gateway
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u secrets.GHCR_USERNAME --password-stdin
          docker pull ghcr.io/netsepio/gateway:main
          docker run --name="gateway" --env-file=.env -p 3000:3000 --net=bridge -d ghcr.io/netsepio/gateway:main

    - name: Deploy on PROD server 
      if: github.ref == 'refs/heads/prod' 
      uses: appleboy/ssh-action@v0.1.7
      with:         
        host: ${{ secrets.PROD_REMOTE_SERVER_ADDRESS }}
        username: ${{ secrets.PROD_SERVER_USERNAME }}
        key:  ${{ secrets.PROD_REMOTE_SERVER_KEY }}
        port: ${{ secrets.PROD_SSH_PORT }} 
        script: |
          pwd
          cd gateway
          docker stop gateway && docker rm gateway && docker image rm gateway
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u secrets.GHCR_USERNAME --password-stdin
          docker pull ghcr.io/netsepio/gateway:prod
          docker run --name="gateway" --env-file=.env -p 3000:3000 --net=bridge -d ghcr.io/netsepio/gateway:prod    